
import re

with open('src/data/players.ts', 'r', encoding='utf-8') as f:
    text = f.read()

# Add status and isCardEligible to existing players
# Find all occurrences of priceHistory: [ ... ] and add status and isCardEligible if not present
def replacer(match):
    block = match.group(0)
    if 'status:' not in block:
        block += "
    status: 'active',
    isCardEligible: true,"
    return block

text = re.sub(r'priceHistory:\s*\[[\s\S]*?\](?=,)', replacer, text)

# Now prepare additional active players
additional_active_players = [
    # --- PREMIER LEAGUE ---
    {
        "id": "p-foden-47",
        "name": "フィル・フォーデン",
        "kanaName": "フィル・フォーデン",
        "enName": "Phil Foden",
        "club": "マンチェスター・シティ",
        "league": "プレミアリーグ",
        "nationality": "イングランド",
        "position": "RWG",
        "number": 47,
        "ovr": 90,
        "rarity": "SSR",
        "age": 24,
        "height": 171,
        "foot": "左",
        "careerBio": "卓越したボールコントロールと機敏な身のこなしで相手守備を切り裂くイングランドの若き魔術師。",
        "baseIssueCount": 2000,
        "remainingIssueCount": 1950,
        "basePrice": 180000,
        "priceHistory": [{"date": "09/14", "price": 175000}, {"date": "09/20", "price": 180000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-palmer-20",
        "name": "コール・パーマー",
        "kanaName": "コール・パーマー",
        "enName": "Cole Palmer",
        "club": "チェルシー",
        "league": "プレミアリーグ",
        "nationality": "イングランド",
        "position": "AMF",
        "number": 20,
        "ovr": 89,
        "rarity": "SR",
        "age": 22,
        "height": 189,
        "foot": "左",
        "careerBio": "『コールド・パーマー』の愛称通り、氷のように冷静な判断力と決定的なラストパスでチェルシーの攻撃を牽引。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4890,
        "basePrice": 95000,
        "priceHistory": [{"date": "09/14", "price": 90000}, {"date": "09/20", "price": 95000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-saliba-02",
        "name": "ウィリアム・サリバ",
        "kanaName": "ウィリアム・サリバ",
        "enName": "William Saliba",
        "club": "アーセナル",
        "league": "プレミアリーグ",
        "nationality": "フランス",
        "position": "CB",
        "number": 2,
        "ovr": 89,
        "rarity": "SR",
        "age": 23,
        "height": 192,
        "foot": "右",
        "careerBio": "相手ストライカーを完全に封殺する世界最高峰のセンターバック。スピード、対人、ビルドアップの全要素で圧倒。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4800,
        "basePrice": 88000,
        "priceHistory": [{"date": "09/14", "price": 85000}, {"date": "09/20", "price": 88000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-rice-41",
        "name": "デクラン・ライス",
        "kanaName": "デクラン・ライス",
        "enName": "Declan Rice",
        "club": "アーセナル",
        "league": "プレミアリーグ",
        "nationality": "イングランド",
        "position": "DMF",
        "number": 41,
        "ovr": 90,
        "rarity": "SSR",
        "age": 25,
        "height": 188,
        "foot": "右",
        "careerBio": "中盤全域を制圧する絶対的フィルター。ボール奪取能力のみならず強烈なミドルシュートと推進力でアーセナルを支える。",
        "baseIssueCount": 2000,
        "remainingIssueCount": 1960,
        "basePrice": 175000,
        "priceHistory": [{"date": "09/14", "price": 170000}, {"date": "09/20", "price": 175000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-alisson-01",
        "name": "アリソン・ベッカー",
        "kanaName": "アリソン・ベッカー",
        "enName": "Alisson Becker",
        "club": "リヴァプール",
        "league": "プレミアリーグ",
        "nationality": "ブラジル",
        "position": "GK",
        "number": 1,
        "ovr": 91,
        "rarity": "SSR",
        "age": 31,
        "height": 193,
        "foot": "右",
        "careerBio": "1対1の神がかったセーブと的確なポジショニングでリヴァプールのゴールマウスを死守する世界屈指の守護神。",
        "baseIssueCount": 2000,
        "remainingIssueCount": 1970,
        "basePrice": 165000,
        "priceHistory": [{"date": "09/14", "price": 160000}, {"date": "09/20", "price": 165000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-alexanderarnold-66",
        "name": "トレント・A・アーノルド",
        "kanaName": "トレント・アレクサンダー・アーノルド",
        "enName": "Trent Alexander-Arnold",
        "club": "リヴァプール",
        "league": "プレミアリーグ",
        "nationality": "イングランド",
        "position": "RB",
        "number": 66,
        "ovr": 88,
        "rarity": "SR",
        "age": 25,
        "height": 175,
        "foot": "右",
        "careerBio": "MF顔負けの高精度ロングフィードとFKで局面を一撃で打開する、世界最高峰のプレーメーカー型右サイドバック。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4750,
        "basePrice": 82000,
        "priceHistory": [{"date": "09/14", "price": 80000}, {"date": "09/20", "price": 82000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-brunofernandes-08",
        "name": "ブルーノ・フェルナンデス",
        "kanaName": "ブルーノ・フェルナンデス",
        "enName": "Bruno Fernandes",
        "club": "マンチェスター・ユナイテッド",
        "league": "プレミアリーグ",
        "nationality": "ポルトガル",
        "position": "AMF",
        "number": 8,
        "ovr": 88,
        "rarity": "SR",
        "age": 30,
        "height": 179,
        "foot": "右",
        "careerBio": "驚異的なチャンス創出数と闘志でマンチェスター・ユナイテッドのキャプテンとして前線を統率する司令塔。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4700,
        "basePrice": 78000,
        "priceHistory": [{"date": "09/14", "price": 76000}, {"date": "09/20", "price": 78000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-watkins-11",
        "name": "オリー・ワトキンス",
        "kanaName": "オリー・ワトキンス",
        "enName": "Ollie Watkins",
        "club": "アストン・ヴィラ",
        "league": "プレミアリーグ",
        "nationality": "イングランド",
        "position": "CF",
        "number": 11,
        "ovr": 86,
        "rarity": "SR",
        "age": 28,
        "height": 180,
        "foot": "右",
        "careerBio": "裏への鋭い抜け出しとアシスト能力を兼備し、アストン・ヴィラをCL出場へと導いた万能型ストライカー。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4850,
        "basePrice": 65000,
        "priceHistory": [{"date": "09/14", "price": 62000}, {"date": "09/20", "price": 65000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-isak-14",
        "name": "アレクサンデル・イサク",
        "kanaName": "アレクサンデル・イサク",
        "enName": "Alexander Isak",
        "club": "ニューカッスル",
        "league": "プレミアリーグ",
        "nationality": "スウェーデン",
        "position": "CF",
        "number": 14,
        "ovr": 87,
        "rarity": "SR",
        "age": 25,
        "height": 192,
        "foot": "右",
        "careerBio": "しなやかなドリブルと長身を生かしたポストワーク、そして冷静無比なフィニッシュで得点を量産する大型FW。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4800,
        "basePrice": 72000,
        "priceHistory": [{"date": "09/14", "price": 70000}, {"date": "09/20", "price": 72000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-macallister-10",
        "name": "アレクシス・マック・アリスター",
        "kanaName": "アレクシス・マック・アリスター",
        "enName": "Alexis Mac Allister",
        "club": "リヴァプール",
        "league": "プレミアリーグ",
        "nationality": "アルゼンチン",
        "position": "CMF",
        "number": 10,
        "ovr": 87,
        "rarity": "SR",
        "age": 25,
        "height": 176,
        "foot": "右",
        "careerBio": "W杯王者アルゼンチンの心臓。巧みなボールキープとテンポメイク、強烈なミドルシュートでリヴァプールの中盤に君臨。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4820,
        "basePrice": 74000,
        "priceHistory": [{"date": "09/14", "price": 72000}, {"date": "09/20", "price": 74000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-gvardiol-24",
        "name": "ヨシュコ・グヴァルディオル",
        "kanaName": "ヨシュコ・グヴァルディオル",
        "enName": "Josko Gvardiol",
        "club": "マンチェスター・シティ",
        "league": "プレミアリーグ",
        "nationality": "クロアチア",
        "position": "LB",
        "number": 24,
        "ovr": 88,
        "rarity": "SR",
        "age": 22,
        "height": 185,
        "foot": "左",
        "careerBio": "強靭なフィジカルと卓越した左足の技術で守備のみならず攻撃の起点としても決定的な仕事を果たすモダンDF。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4810,
        "basePrice": 80000,
        "priceHistory": [{"date": "09/14", "price": 78000}, {"date": "09/20", "price": 80000}],
        "status": "active",
        "isCardEligible": True
    },

    # --- LA LIGA ---
    {
        "id": "p-raphinha-11",
        "name": "ハフィーニャ",
        "kanaName": "ハフィーニャ",
        "enName": "Raphinha",
        "club": "バルセロナ",
        "league": "ラ・リーガ",
        "nationality": "ブラジル",
        "position": "LWG",
        "number": 11,
        "ovr": 88,
        "rarity": "SR",
        "age": 27,
        "height": 176,
        "foot": "左",
        "careerBio": "強烈なプレッシングとダイナミックな左足シュートでバルサの攻撃を牽引するブラジリアンウインガー。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4780,
        "basePrice": 83000,
        "priceHistory": [{"date": "09/14", "price": 81000}, {"date": "09/20", "price": 83000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-daniolmo-20",
        "name": "ダニ・オルモ",
        "kanaName": "ダニ・オルモ",
        "enName": "Dani Olmo",
        "club": "バルセロナ",
        "league": "ラ・リーガ",
        "nationality": "スペイン",
        "position": "AMF",
        "number": 20,
        "ovr": 87,
        "rarity": "SR",
        "age": 26,
        "height": 179,
        "foot": "右",
        "careerBio": "EURO2024得点王の一人。狭いエリアでの華麗なターンと決定的なラストパスでゲームを掌握する天才司令塔。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4830,
        "basePrice": 76000,
        "priceHistory": [{"date": "09/14", "price": 74000}, {"date": "09/20", "price": 76000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-cubarsi-02",
        "name": "パウ・クバルシ",
        "kanaName": "パウ・クバルシ",
        "enName": "Pau Cubarsí",
        "club": "バルセロナ",
        "league": "ラ・リーガ",
        "nationality": "スペイン",
        "position": "CB",
        "number": 2,
        "ovr": 84,
        "rarity": "R",
        "age": 17,
        "height": 184,
        "foot": "右",
        "careerBio": "ラ・マシアが生んだ新時代の神童DF。10代とは思えない卓越した戦術眼と正確無比な縦パスで最終ラインを統率。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14600,
        "basePrice": 24000,
        "priceHistory": [{"date": "09/14", "price": 22000}, {"date": "09/20", "price": 24000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-camavinga-06",
        "name": "エドゥアルド・カマヴィンガ",
        "kanaName": "エドゥアルド・カマヴィンガ",
        "enName": "Eduardo Camavinga",
        "club": "レアル・マドリード",
        "league": "ラ・リーガ",
        "nationality": "フランス",
        "position": "CMF",
        "number": 6,
        "ovr": 87,
        "rarity": "SR",
        "age": 21,
        "height": 182,
        "foot": "左",
        "careerBio": "驚異的なボール奪取と推進力、複数ポジションを完璧にこなす戦術的多才さでマドリーの未来を担う逸材。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4790,
        "basePrice": 78000,
        "priceHistory": [{"date": "09/14", "price": 75000}, {"date": "09/20", "price": 78000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-tchouameni-14",
        "name": "オーレリアン・チュアメニ",
        "kanaName": "オーレリアン・チュアメニ",
        "enName": "Aurélien Tchouaméni",
        "club": "レアル・マドリード",
        "league": "ラ・リーガ",
        "nationality": "フランス",
        "position": "DMF",
        "number": 14,
        "ovr": 88,
        "rarity": "SR",
        "age": 24,
        "height": 187,
        "foot": "右",
        "careerBio": "空中戦と地上戦の両面で圧倒的なデュエル勝率を誇り、中盤の要所としてマドリーの屋台骨を支える要塞。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4810,
        "basePrice": 80000,
        "priceHistory": [{"date": "09/14", "price": 78000}, {"date": "09/20", "price": 80000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-nicowilliams-10",
        "name": "ニコ・ウィリアムズ",
        "kanaName": "ニコ・ウィリアムズ",
        "enName": "Nico Williams",
        "club": "アスレティック・ビルバオ",
        "league": "ラ・リーガ",
        "nationality": "スペイン",
        "position": "LWG",
        "number": 10,
        "ovr": 88,
        "rarity": "SR",
        "age": 22,
        "height": 181,
        "foot": "右",
        "careerBio": "EURO2024で世界を震撼させた電光石火のスピードスター。両足から繰り出される高速クロスとカットインシュートは脅威そのもの。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4740,
        "basePrice": 85000,
        "priceHistory": [{"date": "09/14", "price": 82000}, {"date": "09/20", "price": 85000}],
        "status": "active",
        "isCardEligible": True
    },

    # --- SERIE A ---
    {
        "id": "p-calhanoglu-20",
        "name": "ハカン・チャルハノール",
        "kanaName": "ハカン・チャルハノール",
        "enName": "Hakan Calhanoglu",
        "club": "インテル",
        "league": "セリエA",
        "nationality": "トルコ",
        "position": "DMF",
        "number": 20,
        "ovr": 88,
        "rarity": "SR",
        "age": 30,
        "height": 178,
        "foot": "右",
        "careerBio": "レジスタとしてインテルのセリエA制覇を司った司令塔。芸術的FKと寸分狂わぬ展開力で攻撃のタクトを振る。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4840,
        "basePrice": 77000,
        "priceHistory": [{"date": "09/14", "price": 75000}, {"date": "09/20", "price": 77000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-dimarco-32",
        "name": "フェデリコ・ディマルコ",
        "kanaName": "フェデリコ・ディマルコ",
        "enName": "Federico Dimarco",
        "club": "インテル",
        "league": "セリエA",
        "nationality": "イタリア",
        "position": "LB",
        "number": 32,
        "ovr": 87,
        "rarity": "SR",
        "age": 26,
        "height": 175,
        "foot": "左",
        "careerBio": "左足から放たれる高精度クロスとスーパーボレーで幾度となくスタジアムを熱狂させるイタリア代表屈指のサイド職人。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4860,
        "basePrice": 72000,
        "priceHistory": [{"date": "09/14", "price": 70000}, {"date": "09/20", "price": 72000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-koopmeiners-08",
        "name": "テーン・コープマイネルス",
        "kanaName": "テーン・コープマイネルス",
        "enName": "Teun Koopmeiners",
        "club": "ユヴェントス",
        "league": "セリエA",
        "nationality": "オランダ",
        "position": "AMF",
        "number": 8,
        "ovr": 86,
        "rarity": "SR",
        "age": 26,
        "height": 183,
        "foot": "左",
        "careerBio": "アタランタのEL優勝に貢献しユヴェントスへ移籍。強烈なミドルと戦術眼でゲームを組み立てるオランダ代表MF。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4880,
        "basePrice": 66000,
        "priceHistory": [{"date": "09/14", "price": 64000}, {"date": "09/20", "price": 66000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-bremer-03",
        "name": "グレイソン・ブレーメル",
        "kanaName": "グレイソン・ブレーメル",
        "enName": "Gleison Bremer",
        "club": "ユヴェントス",
        "league": "セリエA",
        "nationality": "ブラジル",
        "position": "CB",
        "number": 3,
        "ovr": 87,
        "rarity": "SR",
        "age": 27,
        "height": 188,
        "foot": "右",
        "careerBio": "セリエA年間最優秀DF受賞の実績を誇る鉄壁のセンターバック。圧倒的な跳躍力と対人力で相手FWを完全に封殺。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4870,
        "basePrice": 71000,
        "priceHistory": [{"date": "09/14", "price": 69000}, {"date": "09/20", "price": 71000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-lookman-11",
        "name": "アデモラ・ルックマン",
        "kanaName": "アデモラ・ルックマン",
        "enName": "Ademola Lookman",
        "club": "アタランタ",
        "league": "セリエA",
        "nationality": "ナイジェリア",
        "position": "LWG",
        "number": 11,
        "ovr": 86,
        "rarity": "SR",
        "age": 26,
        "height": 174,
        "foot": "右",
        "careerBio": "EL決勝で圧巻のハットトリックを記録し欧州王座をもたらしたアタランタの英雄。鋭敏なドリブルと高い決定力が武器。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4860,
        "basePrice": 65000,
        "priceHistory": [{"date": "09/14", "price": 63000}, {"date": "09/20", "price": 65000}],
        "status": "active",
        "isCardEligible": True
    },

    # --- BUNDESLIGA ---
    {
        "id": "p-xhaka-34",
        "name": "グラニト・ジャカ",
        "kanaName": "グラニト・ジャカ",
        "enName": "Granit Xhaka",
        "club": "レヴァークーゼン",
        "league": "ブンデスリーガ",
        "nationality": "スイス",
        "position": "DMF",
        "number": 34,
        "ovr": 88,
        "rarity": "SR",
        "age": 31,
        "height": 185,
        "foot": "左",
        "careerBio": "レヴァークーゼンの歴史的無敗優勝を成し遂げたキャプテンシーの象徴。的確なパスワークと鋼の統率力でピッチを支配。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4820,
        "basePrice": 78000,
        "priceHistory": [{"date": "09/14", "price": 76000}, {"date": "09/20", "price": 78000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-grimaldo-20",
        "name": "アレハンドロ・グリマルド",
        "kanaName": "アレハンドロ・グリマルド",
        "enName": "Alejandro Grimaldo",
        "club": "レヴァークーゼン",
        "league": "ブンデスリーガ",
        "nationality": "スペイン",
        "position": "LB",
        "number": 20,
        "ovr": 87,
        "rarity": "SR",
        "age": 28,
        "height": 171,
        "foot": "左",
        "careerBio": "サイドバックの枠を超えた驚異的なゴール数とアシスト数を叩き出す左足の魔術師。FKの精度は世界屈指。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4840,
        "basePrice": 73000,
        "priceHistory": [{"date": "09/14", "price": 71000}, {"date": "09/20", "price": 73000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-guirassy-09",
        "name": "セール・ギラシ",
        "kanaName": "セール・ギラシ",
        "enName": "Serhou Guirassy",
        "club": "ドルトムント",
        "league": "ブンデスリーガ",
        "nationality": "ギニア",
        "position": "CF",
        "number": 9,
        "ovr": 86,
        "rarity": "SR",
        "age": 28,
        "height": 187,
        "foot": "右",
        "careerBio": "驚異的な決定力でブンデスリーガ得点ランキング上位を席巻した大型ストライカー。ドルトムントの最前線を牽引。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4870,
        "basePrice": 67000,
        "priceHistory": [{"date": "09/14", "price": 65000}, {"date": "09/20", "price": 67000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-simons-10",
        "name": "シャビ・シモンズ",
        "kanaName": "シャビ・シモンズ",
        "enName": "Xavi Simons",
        "club": "RBライプツィヒ",
        "league": "ブンデスリーガ",
        "nationality": "オランダ",
        "position": "AMF",
        "number": 10,
        "ovr": 87,
        "rarity": "SR",
        "age": 21,
        "height": 179,
        "foot": "右",
        "careerBio": "圧倒的な加速力と閃きのラストパスで欧州中のビッグクラブから注目を集めるオランダの新世代アタッカー。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4810,
        "basePrice": 79000,
        "priceHistory": [{"date": "09/14", "price": 76000}, {"date": "09/20", "price": 79000}],
        "status": "active",
        "isCardEligible": True
    },

    # --- LIGUE 1 ---
    {
        "id": "p-barcola-29",
        "name": "ブラッドリー・バルコラ",
        "kanaName": "ブラッドリー・バルコラ",
        "enName": "Bradley Barcola",
        "club": "パリ・サンジェルマン",
        "league": "リーグ・アン",
        "nationality": "フランス",
        "position": "LWG",
        "number": 29,
        "ovr": 86,
        "rarity": "SR",
        "age": 22,
        "height": 182,
        "foot": "右",
        "careerBio": "PSGの左ウイングとして爆発的な加速と高精度のフィニッシュで得点を重ねるフランス期待の若き快足FW。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4860,
        "basePrice": 68000,
        "priceHistory": [{"date": "09/14", "price": 65000}, {"date": "09/20", "price": 68000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-vitinha-17",
        "name": "ヴィティーニャ",
        "kanaName": "ヴィティーニャ",
        "enName": "Vitinha",
        "club": "パリ・サンジェルマン",
        "league": "リーグ・アン",
        "nationality": "ポルトガル",
        "position": "CMF",
        "number": 17,
        "ovr": 87,
        "rarity": "SR",
        "age": 24,
        "height": 172,
        "foot": "右",
        "careerBio": "高いプレス耐性と的確な配球力でPSGとポルトガル代表の中盤にリズムを生み出すプレーメーカー。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4830,
        "basePrice": 75000,
        "priceHistory": [{"date": "09/14", "price": 73000}, {"date": "09/20", "price": 75000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-zaireemery-33",
        "name": "W・ザイール・エメリ",
        "kanaName": "ワレン・ザイール・エメリ",
        "enName": "Warren Zaïre-Emery",
        "club": "パリ・サンジェルマン",
        "league": "リーグ・アン",
        "nationality": "フランス",
        "position": "CMF",
        "number": 33,
        "ovr": 84,
        "rarity": "R",
        "age": 18,
        "height": 178,
        "foot": "右",
        "careerBio": "10代にしてフランス代表デビューを飾ったPSGアカデミー最高傑作。卓越したフィジカルとインテリジェンスを兼備。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14700,
        "basePrice": 26000,
        "priceHistory": [{"date": "09/14", "price": 24000}, {"date": "09/20", "price": 26000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-jonathandavid-09",
        "name": "ジョナサン・デイヴィッド",
        "kanaName": "ジョナサン・デイヴィッド",
        "enName": "Jonathan David",
        "club": "リール",
        "league": "リーグ・アン",
        "nationality": "カナダ",
        "position": "CF",
        "number": 9,
        "ovr": 85,
        "rarity": "R",
        "age": 24,
        "height": 177,
        "foot": "右",
        "careerBio": "リーグ・アンで毎年コンスタントに20ゴール近くを記録するカナダ代表エース。ボックス内での決定力は抜群。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14650,
        "basePrice": 32000,
        "priceHistory": [{"date": "09/14", "price": 30000}, {"date": "09/20", "price": 32000}],
        "status": "active",
        "isCardEligible": True
    },

    # --- SAMURAI BLUE & J1 LEAGUE STARS ---
    {
        "id": "p-morita-05",
        "name": "守田英正",
        "kanaName": "モリタ ヒデマサ",
        "enName": "Hidemasa Morita",
        "club": "スポルティングCP",
        "league": "ポルトガル・リーグ",
        "nationality": "日本",
        "position": "DMF",
        "number": 5,
        "ovr": 85,
        "rarity": "R",
        "age": 29,
        "height": 177,
        "foot": "右",
        "careerBio": "スポルティングのリーグ制覇に不可欠な羅針盤。戦術的知性と的確なポジショニングで攻守のバランスを保つ日本代表MF。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14500,
        "basePrice": 31000,
        "priceHistory": [{"date": "09/14", "price": 29000}, {"date": "09/20", "price": 31000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-kamada-18",
        "name": "鎌田大地",
        "kanaName": "カマダ ダイチ",
        "enName": "Daichi Kamada",
        "club": "クリスタル・パレス",
        "league": "プレミアリーグ",
        "nationality": "日本",
        "position": "AMF",
        "number": 18,
        "ovr": 84,
        "rarity": "R",
        "age": 28,
        "height": 184,
        "foot": "右",
        "careerBio": "欧州カップ戦での勝負強さと洗練されたボールタッチを誇るアタッカー。プレミアの舞台で輝きを放つ。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14600,
        "basePrice": 28000,
        "priceHistory": [{"date": "09/14", "price": 26000}, {"date": "09/20", "price": 28000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-ueda-09",
        "name": "上田綺世",
        "kanaName": "ウエダ アヤセ",
        "enName": "Ayase Ueda",
        "club": "フェイエノールト",
        "league": "エールディヴィジ",
        "nationality": "日本",
        "position": "CF",
        "number": 9,
        "ovr": 83,
        "rarity": "R",
        "age": 26,
        "height": 182,
        "foot": "右",
        "careerBio": "圧倒的な跳躍力と理不尽なまでのシュートインパクトでゴールネットを揺らす日本代表ストライカー。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14750,
        "basePrice": 22000,
        "priceHistory": [{"date": "09/14", "price": 20000}, {"date": "09/20", "price": 22000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-machida-16",
        "name": "町田浩樹",
        "kanaName": "マチダ コウキ",
        "enName": "Koki Machida",
        "club": "ユニオンSG",
        "league": "ベルギー・リーグ",
        "nationality": "日本",
        "position": "CB",
        "number": 16,
        "ovr": 83,
        "rarity": "R",
        "age": 27,
        "height": 190,
        "foot": "左",
        "careerBio": "190cmの体躯と左足の高精度フィードを併せ持つ大型センターバック。日本代表守備陣に欠かせない要。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14800,
        "basePrice": 21000,
        "priceHistory": [{"date": "09/14", "price": 19000}, {"date": "09/20", "price": 21000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-osako-10",
        "name": "大迫勇也",
        "kanaName": "オオサコ ユウヤ",
        "enName": "Yuya Osako",
        "club": "ヴィッセル神戸",
        "league": "J1リーグ",
        "nationality": "日本",
        "position": "CF",
        "number": 10,
        "ovr": 86,
        "rarity": "SR",
        "age": 34,
        "height": 182,
        "foot": "右",
        "careerBio": "J1年間MVP・得点王。相手を背負ったポストプレーの精度は日本サッカー史上屈指。神戸の初優勝を牽引。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4780,
        "basePrice": 69000,
        "priceHistory": [{"date": "09/14", "price": 66000}, {"date": "09/20", "price": 69000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-muto-11",
        "name": "武藤嘉紀",
        "kanaName": "ムトウ ヨシノリ",
        "enName": "Yoshinori Muto",
        "club": "ヴィッセル神戸",
        "league": "J1リーグ",
        "nationality": "日本",
        "position": "RWG",
        "number": 11,
        "ovr": 84,
        "rarity": "R",
        "age": 32,
        "height": 178,
        "foot": "右",
        "careerBio": "ダイナミックなスプリントと強靭なフィジカルで攻守にわたって絶大な影響力を放つ神戸の看板アタッカー。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14700,
        "basePrice": 25000,
        "priceHistory": [{"date": "09/14", "price": 23000}, {"date": "09/20", "price": 25000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-nishikawa-01",
        "name": "西川周作",
        "kanaName": "ニシカワ シュウサク",
        "enName": "Shusaku Nishikawa",
        "club": "浦和レッズ",
        "league": "J1リーグ",
        "nationality": "日本",
        "position": "GK",
        "number": 1,
        "ovr": 84,
        "rarity": "R",
        "age": 38,
        "height": 183,
        "foot": "左",
        "careerBio": "ACL制覇とJリーグ通算出場記録を更新し続ける生ける伝説GK。左足の低弾道パントキックは世界基準。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14600,
        "basePrice": 23000,
        "priceHistory": [{"date": "09/14", "price": 21000}, {"date": "09/20", "price": 23000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-andersonlopes-11",
        "name": "アンデルソン・ロペス",
        "kanaName": "アンデルソン・ロペス",
        "enName": "Anderson Lopes",
        "club": "横浜F・マリノス",
        "league": "J1リーグ",
        "nationality": "ブラジル",
        "position": "CF",
        "number": 11,
        "ovr": 85,
        "rarity": "R",
        "age": 31,
        "height": 185,
        "foot": "左",
        "careerBio": "J1得点王に輝いた驚異のゴールハンター。左足の強烈なシュートと高い空中戦勝率でマリノスの最前線を支える。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14650,
        "basePrice": 29000,
        "priceHistory": [{"date": "09/14", "price": 27000}, {"date": "09/20", "price": 29000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-hosoya-19",
        "name": "細谷真大",
        "kanaName": "ホソヤ マオ",
        "enName": "Mao Hosoya",
        "club": "柏レイソル",
        "league": "J1リーグ",
        "nationality": "日本",
        "position": "CF",
        "number": 19,
        "ovr": 82,
        "rarity": "R",
        "age": 23,
        "height": 177,
        "foot": "右",
        "careerBio": "パリ五輪でも輝きを放った日本代表の若き重戦車FW。屈強なボディバランスと鋭いターンからの強打が魅力。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14850,
        "basePrice": 18000,
        "priceHistory": [{"date": "09/14", "price": 16000}, {"date": "09/20", "price": 18000}],
        "status": "active",
        "isCardEligible": True
    },

    # --- SOUTH AMERICAN & INTERNATIONAL STARS ---
    {
        "id": "p-neymar-10",
        "name": "ネイマール Jr.",
        "kanaName": "ネイマール",
        "enName": "Neymar Jr.",
        "club": "アル・ヒラル",
        "league": "サウジ・プロ",
        "nationality": "ブラジル",
        "position": "LWG",
        "number": 10,
        "ovr": 92,
        "rarity": "SSR",
        "age": 32,
        "height": 175,
        "foot": "両足",
        "careerBio": "ブラジル代表歴代最多得点記録保持者。閃きに満ちたサンバのリズムと世界一のテクニックでファンを魅了し続ける天才。",
        "baseIssueCount": 2000,
        "remainingIssueCount": 1960,
        "basePrice": 185000,
        "priceHistory": [{"date": "09/14", "price": 178000}, {"date": "09/20", "price": 185000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-suarez-09",
        "name": "ルイス・スアレス",
        "kanaName": "ルイス・スアレス",
        "enName": "Luis Suárez",
        "club": "インテル・マイアミ",
        "league": "MLS",
        "nationality": "ウルグアイ",
        "position": "CF",
        "number": 9,
        "ovr": 88,
        "rarity": "SR",
        "age": 37,
        "height": 182,
        "foot": "右",
        "careerBio": "通算500ゴール超の世界的点取り屋。盟友メッシと共にマイアミの地で今なお衰えぬ得点嗅覚を発揮し続けるレジェンド。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4750,
        "basePrice": 82000,
        "priceHistory": [{"date": "09/14", "price": 80000}, {"date": "09/20", "price": 82000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-endrick-16",
        "name": "エンドリッキ",
        "kanaName": "エンドリッキ",
        "enName": "Endrick",
        "club": "レアル・マドリード",
        "league": "ラ・リーガ",
        "nationality": "ブラジル",
        "position": "CF",
        "number": 16,
        "ovr": 85,
        "rarity": "R",
        "age": 18,
        "height": 173,
        "foot": "左",
        "careerBio": "ブラジルの至宝。爆発的なパワーと左足のキャノンシュートで世界を驚かせる超新星ストライカー。",
        "baseIssueCount": 15000,
        "remainingIssueCount": 14500,
        "basePrice": 35000,
        "priceHistory": [{"date": "09/14", "price": 32000}, {"date": "09/20", "price": 35000}],
        "status": "active",
        "isCardEligible": True
    },
    {
        "id": "p-gyokeres-09",
        "name": "ヴィクトル・ギョケレシュ",
        "kanaName": "ヴィクトル・ギョケレシュ",
        "enName": "Viktor Gyökeres",
        "club": "スポルティングCP",
        "league": "ポルトガル・リーグ",
        "nationality": "スウェーデン",
        "position": "CF",
        "number": 9,
        "ovr": 89,
        "rarity": "SR",
        "age": 26,
        "height": 187,
        "foot": "右",
        "careerBio": "欧州得点王争いをリードする怪力ストライカー。相手DFを薙ぎ倒して突き進む規格外の破壊力でゴールを量産。",
        "baseIssueCount": 5000,
        "remainingIssueCount": 4780,
        "basePrice": 92000,
        "priceHistory": [{"date": "09/14", "price": 88000}, {"date": "09/20", "price": 92000}],
        "status": "active",
        "isCardEligible": True
    }
]

print('Parsed additional players successfully:', len(additional_active_players))
